### ISSUE TITLE
 Unknown websocket error

### ISSUE THREAD

**Issue by Alacon** [kenyee/android-ddp-client#10]
Hi,

I´m creating an app to communicate with my meteor app. But I  am not able to connect to my meteor app or demoparties.meteor.com.

I'm using Android Studio 0.8.6
Android-DDP-Client 0.5.7.6
Java-DDP-client 0.5.7.6
 
This is the error I recieve
I/DDPStateSingleton﹕ createDDPClient on server: demoparties.meteor.com  port: 80
I/DDPStateSingleton﹕ createDDPClient mDDP: com.keysolutions.ddpclient.DDPClient@426043f8
V/DDPStateSingleton﹕ isConnected - state:Disconnected

V/DDPStateSingleton﹕ broadcastDDPError - errorMsg = [Unknown websocket error (exception in callback?)]
V/DDPStateSingleton﹕ getState: Closed
D/Connection Issue﹕ Error connecting to server...please try again
I/DDPStateSingleton﹕ connectIfNeeded
I/DDPStateSingleton﹕ connectIfNeeded - currently closed connection > Re-connect
I/DDPStateSingleton﹕ createDDPClient on server: demoparties.meteor.com  port: 80
I/DDPStateSingleton﹕ createDDPClient mDDP: com.keysolutions.ddpclient.DDPClient@425f7fe0

D/Login Error﹕ Unknown websocket error (exception in callback?)

What can I do?

/Pelle

**Comment by shantanubhadoria** [comment]
Hi @kenyee 
I am getting the same error. Any idea about this?
