### ISSUE TITLE
login from android client

### ISSUE THREAD

**Issue by bswcube** [kenyee/android-ddp-client#14]
I created a website using meteor.js, and I am using accounts-google, accounts-twitter, and accounts-facebook packages for login purposes. I want to create a native android application for the website. I could not figure out how I can login from android by using these 3 packages in meteor app. Can you give me some ideas? thank you.

**Comment by kenyee** [comment]
sorry for the late reply...did you look at the Android Parties sample?
The packages you mention are server-side...not on your Android client...
