### ISSUE TITLE
DDPClient should use SSL connection when constructed with useSSL=true

### ISSUE THREAD

**Issue by mikosik** [kenyee/android-ddp-client#16]
Note: this is bug report against https://github.com/kenyee/java-ddp-client library. I'm reporting it here as issue tracker for java-ddp-client project is disabled and I assume both projects are supported by the same person.

`DDPClient` constructor has `useSSL` argument that indicates that SSL encryption should be used. However setting it to true changes only the port to which client connects (from 80 to 443). It should also configure `WebSocket` to actually use SSL for encrypting socket connection. Example of how to do it can be found at https://github.com/TooTallNate/Java-WebSocket/blob/Java-WebSocket-1.3.0/src/main/example/SSLClientExample.java#L60-L84

**Comment by kenyee** [comment]
Not sure why the issue tracker was disabled on the other project but it's enabled now.
I added code for that but am having problems testing :-(

**Comment by kenyee** [comment]
Released 1.0.0.1 to Maven Central
