### ISSUE TITLE
project

### ISSUE THREAD

**Issue by guoyoujin** [kenyee/android-ddp-client#18]
Hello I now use the eclipse programming, you will get you the project need . Jar package sent to me? thank you

**Comment by kenyee** [comment]
You actually need an AAR not a JAR to link this to your Android app.  They're located here:
https://github.com/kenyee/android-ddp-client/tree/master/build/outputs/aar

**Comment by guoyoujin** [comment]
Thank you very much, this is very helpful to me, I'm trying to meteor combined with android project
