### ISSUE TITLE
Unsubscribe is broken

### ISSUE THREAD

**Issue by TheMedo** [kenyee/android-ddp-client#19]
Here's the code snipped from the _subsribe()_ method
```java 
int id = addCommmand(resultListener/** "sub,"+name+","+Arrays.toString(params* )*/);
subMsg.put(DdpMessageField.ID, Integer.toString(id));
```  
The _addCommand()_ generates a unique integer ID
```java
int id = nextId();
```

Now, when using _unsubscribe()_ method **the same happens** i.e. I get the _nextId()_ instead of the one I need to unsubscribe from the previous subscription, thus `removed` is never called to clear the client collection cache.

**Comment by kenyee** [comment]
sorry...just got to looking at this.
The ID is part of the meteor protocol.
You should be tracking your subscribes via the Meteor subscription name.  Use a Map<String, subscription> to look up your subscription from the name.

**Comment by stephen-workpop** [comment]
```
    public void fixedUnsubscribe(final String subId, final String name)
    {
        if ((subId == null) || (name == null))
        {
            Timber.d("Cannot unsubscribe if subId or name is not specified.");
            return;
        }

        final Map<String, Object> unsubMsg = new HashMap<>();
        unsubMsg.put(DDPClient.DdpMessageField.MSG, DDPClient.DdpMessageType.UNSUB);
        unsubMsg.put(DDPClient.DdpMessageField.NAME, name);
        unsubMsg.put(DDPClient.DdpMessageField.ID, subId);
        getDDP().send(unsubMsg);
    }
```

**Comment by kenyee** [comment]
In version 1.0.0.4 of the java-ddp-client library, you can pass the subscribe ID into the unsubscribe method.
