### ISSUE TITLE
No recovery after network connection loss

### ISSUE THREAD

**Issue by stephen-workpop** [kenyee/android-ddp-client#20]
If you lose your network connection and try to subscribe/unsubscribe, the request is never sent and the error is swallowed with no recovery on reconnection.

The flow goes subscribe() -> send() -> WebsocketNotConnectedException -> handleError() -> generic error. 

When network connectivity comes back, how can we be sure we are in sync and didn't miss any server updates? I am unable to find any code in the library where things are recovered upon reconnection. Is it possible for our client-side collections to get in an invalid state since they missed DDP updates while being disconnected? I am just looking for some advice on how to recover. Thanks!

**Comment by stephen-workpop** [comment]
Another question. For now, when the network connection is lost and then regained, I simply call DDPStateSingleton.connectIfNeeded(); Once I am reconnected to Meteor, I simply re-subscribe to everything I care about and start fresh. Unfortunately, the call to connectIfNeeded() results in so much garbage collection, the app becomes unusable. Do you know what might be causing these GC's or how I can avoid them?

**Comment by kenyee** [comment]
I think this is done server side...it tracks changes for a particular token and should send a bunch of ddp changes responses after reconnection.
