### ISSUE TITLE
broadcastConnectionState() doesn't listen for "closed" state

### ISSUE THREAD

**Issue by stephen-workpop** [kenyee/android-ddp-client#21]
I think broadcastConnectionState() is broken in that it doesn't report connection closed events when the WebSocket loses its connection due to the app idling too long or network loss.

To get around this, I added my own observer on the DDPClient and listened for DDPClient.DdpMessageType.CLOSED.

I think this is a bit weird though that this constant is considered a “DDP message type” because “closed” is not really a DDP message. The library internally sends the closed message to its listeners when the web socket connection is broken. There isn’t a closed message in the official DDP protocol specification. 

```
getDDP().addObserver(new Observer()
        {
            @Override
            public void update(final Observable observable, final Object object)
            {
                if (object instanceof Map<?, ?>)
                {
                    final Map<String, Object> jsonFields = (Map<String, Object>) object;
                    final String msg = (String) jsonFields.get(DDPClient.DdpMessageField.MSG);
                    if (DDPClient.DdpMessageType.CLOSED.equals(msg))
                    {
                        broadcastConnectionState(DDPSTATE.Closed);
                    }
                }
            }
        });
```

**Comment by William-Hoang** [comment]
Hi stephen-workpop,
Thank for your code, it saves me a lot of time to find out the issue. sometimes my app run and receive nothing. With your code I saw message closed from DDPClient in that case.

Do you know why it send closed message and how to resolve it? Thanks.

**Comment by stephen-workpop** [comment]
If you use my code above, you will get a DDPState.Closed passed to broadCastConnectionState(). When that happens, it usually means your WebSocket connection with the Meteor server has been lost. In my case, I see this message when we are rolling out new code to the server and it has to restart. When I get the closed message, I plan on trying to reconnect with connectIfNeeded(). It might also be a good idea to use exponential back off with each reconnect try.

**Comment by kenyee** [comment]
Sorry about the weirdness w/ the DdpMessageType.Closed msg.  It's because there wasn't a good way to notify listeners w/o a command ID...the closed msg seemed like something the listeners should be expecting instead (an analogue to the connected and login msgs).
I added the missing broadcast in version 1.0.2.0 of the android-ddp-client
