### ISSUE TITLE
broadcastConnectionState() signals state change before state variables set

### ISSUE THREAD

**Issue by stephen-workpop** [kenyee/android-ddp-client#22]
broadcastConnectionState() signals that the connection state has changed before the variables that DDPStateSingleton.isConnected() uses have been updated. I ran into a bug because my implementation of broadcastConnectionState() called another method that relied on DDPStateSingleton.isConnected() being correct. 

I think this can be fixed if you move the observer notification in DDPClient.received() to the bottom of the method after mConnState has been updated rather than notifying observers before updating those variables.

**Comment by kenyee** [comment]
thanks...will look into it

**Comment by kenyee** [comment]
fixed in version 1.0.0.4 of java-ddp-client library.
