### ISSUE TITLE
Using SSL for meteor socket

### ISSUE THREAD

**Issue by shantanubhadoria** [kenyee/android-ddp-client#24]
Good day,
Is the fix for using wss(ws over ssl) out yet? I have a ssl based connection but I don't know how to tell MyDDPState class to use ssl.
Thanks for the help

I figured it might help if I paste some code

    // My DDPState Class
    public class MyDDPState extends DDPStateSingleton {

       protected static String sMeteorServer = "example.com";
       protected static Integer sMeteorPort = 443;

       private static final String TAG = "MyDDPState";

       private MyDDPState(Context context){
           super(context, sMeteorServer, sMeteorPort);
       }

       public static void initInstance(Context context) {
           if(mInstance == null){
               mInstance = new MyDDPState(context);
           }
       }

       public static MyDDPState getInstance() {
           // Return the instance
           return (MyDDPState) mInstance;
       }
   
       @Override
       protected void createDDPClient() {
           try {
               mDDP = new DDPClient(sMeteorServer, sMeteorPort, true);
           } catch (URISyntaxException e) {
               Log.e(TAG, "Invalid Websocket URL connecting to " + getServerHostname()
                       + ":" + getServerPort());
            }
           getDDP().addObserver(this);
           mDDPState = DDPSTATE.NotLoggedIn;
       }
   
       public void verifyPhone(String phone) {
           Object[] methodArgs = new Object[1];
           methodArgs[0] = phone;
           getDDP().call("requestPhoneVerification", methodArgs);
       }
    }

Also, here is my Application class

    public class MyApplication extends Application {
        private static Context sContext = null;

       @Override
       public void onCreate() {
           super.onCreate();
           MyApplication.sContext = getApplicationContext();
           // Initialize the singletons so their instances
           // are bound to the application process.
           initSingletons();
       }

       private void initSingletons() {
           MyDDPState.initInstance(MyApplication.sContext);
       }
   
       public static Context getAppContext() {
           return MyApplication.sContext;
       }
    }

**Comment by joarobles** [comment]
did it work?

**Comment by kenyee** [comment]
This was fixed w/ java-ddp-client version 1.0.0.2.
